### ISSUE TITLE
Too many missing icons

### ISSUE THREAD

**Issue by IvanDeFelice76** [ju1464/Simply_Circles_Icon_Theme#3]
Too many missing icons: 
AlinkCreator (amule)
DevedeNG
DVD95
Glabels
Boxes
OnionShare
OphCrack
Simplescan
TimeShift
Wxcas (amule)

Too many missing icons complete the package in all the colors that is gorgeous!!!

**Comment by ju1464** [comment]
Added the icons you name except ophcrack, which I can not find the name of the icon (the name of the applications and their corresponding icons is not always the same)
