### ISSUE TITLE
Some icon remain the original, can't resize panel icon

### ISSUE THREAD

**Issue by vitoindelicato** [ju1464/Simply_Circles_Icon_Theme#4]
Hi, as I have already said, certain apps, remain the original, how can I change them?
Moreover, how can I resize panel icon? 
![Screenshot from 2019-05-11 22-00-17](https://user-images.githubusercontent.com/46604674/57574380-4ff5a500-7438-11e9-9ab9-c72c241b925c.png)

**Comment by ju1464** [comment]
Applications installed via snap do not respect the theme of icons, as far as I know, you can not do anything with that, the solution is to change the icon manually.
To change the size of the panel icon, it depends on the panel or widget configuration, or manipulating the index.theme in icon theme folder.

**Comment by vitoindelicato** [comment]
Even manipulating index.theme, size doesn't change

**Comment by ju1464** [comment]
What exactly is the issue? What would you like to do? What panel do you use?
